<?php

declare(strict_types=1);

namespace App\Tests\Service;

use App\Service\ChromePdfGenerator;
use PHPUnit\Framework\TestCase;

final class ChromePdfGeneratorTest extends TestCase
{
    public function testGenerateCreatesPdfFromFile(): void
    {
        $generator = new ChromePdfGenerator();

        $projectDir = \sys_get_temp_dir() . '/pdf-test-' . \uniqid('', true);
        \mkdir($projectDir, 0775, true);

        $inputFile = $projectDir . '/input.html';
        \file_put_contents(
            $inputFile,
            '<!doctype html><html><head><meta charset="utf-8"><title>PDF</title></head><body><h1>From File</h1><p>Generated by Chrome.</p></body></html>'
        );

        $outputDir = __DIR__ . '/../../var/generated-pdf';
        if (!\is_dir($outputDir)) {
            \mkdir($outputDir, 0775, true);
        }

        $outputFile = $outputDir . '/from-file.pdf';
        if (\is_file($outputFile)) {
            \unlink($outputFile);
        }

        $generator->generate(
            inputPath: $inputFile,
            outputPath: $outputFile,
            noSandbox: true,
            timeout: 120,
        );

        self::assertFileExists($outputFile);
        self::assertGreaterThan(0, \filesize($outputFile));
    }

    public function testGenerateFromHtmlCreatesPdf(): void
    {
        $generator = new ChromePdfGenerator();

        $outputDir = __DIR__ . '/../../var/generated-pdf';
        if (!\is_dir($outputDir)) {
            \mkdir($outputDir, 0775, true);
        }

        $outputFile = $outputDir . '/from-html.pdf';
        if (\is_file($outputFile)) {
            \unlink($outputFile);
        }

        $html = '<!doctype html><html><head><meta charset="utf-8"><title>PDF</title></head><body><h1>From HTML</h1><p>Generated by Chrome.</p></body></html>';

        $generator->generateFromHtml(
            html: $html,
            outputPath: $outputFile,
            noSandbox: true,
            timeout: 120,
        );

        self::assertFileExists($outputFile);
        self::assertGreaterThan(0, \filesize($outputFile));
    }

    public function testGenerateFromHtmlFailsWithInvalidBinary(): void
    {
        $this->expectException(\RuntimeException::class);

        $generator = new ChromePdfGenerator();

        $outputDir = __DIR__ . '/../../var/generated-pdf';
        if (!\is_dir($outputDir)) {
            \mkdir($outputDir, 0775, true);
        }

        $outputFile = $outputDir . '/invalid-binary.pdf';

        $generator->generateFromHtml(
            html: '<html><body>Invalid binary</body></html>',
            outputPath: $outputFile,
            chromeBin: 'chrome-binary-does-not-exist',
            noSandbox: true,
            timeout: 5,
        );
    }
}
