<?php

declare(strict_types=1);

namespace App\Tests\Command;

use App\Command\GeneratePdfCommand;
use App\Service\ChromePdfGenerator;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Config\Loader\LoaderInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Tester\CommandTester;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Bundle\BundleInterface;
use Symfony\Component\HttpKernel\KernelInterface;

final class GeneratePdfCommandTest extends TestCase
{
    public function testFailsWhenInputFileIsMissing(): void
    {
        $kernel    = new TestKernel('/tmp');
        $generator = new ChromePdfGenerator();

        $command = new GeneratePdfCommand($kernel, $generator);
        $tester  = new CommandTester($command);

        $exitCode = $tester->execute([
            'input'  => 'missing.html',
            'output' => 'out.pdf',
        ]);

        self::assertSame(Command::FAILURE, $exitCode);
        self::assertStringContainsString('Input file not found', $tester->getDisplay());
    }

    public function testGeneratesPdfSuccessfully(): void
    {
        $projectDir = \sys_get_temp_dir() . '/pdf-test-' . \uniqid('', true);
        \mkdir($projectDir, 0775, true);

        $inputFile = $projectDir . '/input.html';
        \file_put_contents(
            $inputFile,
            '<!doctype html><html><head><meta charset="utf-8"><title>PDF</title></head><body><h1>PDF Example</h1><p>Generated by Chrome.</p></body></html>'
        );

        $outputDir = __DIR__ . '/../../var/generated-pdf';
        if (!\is_dir($outputDir)) {
            \mkdir($outputDir, 0775, true);
        }
        $outputFile = $outputDir . '/output.pdf';

        $kernel = new TestKernel($projectDir);

        $generator = new ChromePdfGenerator();

        $command = new GeneratePdfCommand($kernel, $generator);
        $tester  = new CommandTester($command);

        $exitCode = $tester->execute([
            'input'        => $inputFile,
            'output'       => $outputFile,
            '--no-sandbox' => true,
            '--timeout'    => '120',
        ]);

        self::assertSame(Command::SUCCESS, $exitCode);
        self::assertStringContainsString('PDF created at', $tester->getDisplay());
        self::assertFileExists($outputFile);
        self::assertGreaterThan(0, \filesize($outputFile));
    }

    public function testFailsWhenOutputDirectoryIsFile(): void
    {
        $projectDir = \sys_get_temp_dir() . '/pdf-test-' . \uniqid('', true);
        \mkdir($projectDir, 0775, true);

        $inputFile = $projectDir . '/input.html';
        \file_put_contents($inputFile, '<html><body>Test</body></html>');

        $outputDir = $projectDir . '/var/generated-pdf';
        \mkdir(\dirname($outputDir), 0775, true);
        \file_put_contents($outputDir, 'not-a-directory');

        $outputFile = $outputDir . '/output.pdf';

        $kernel = new TestKernel($projectDir);

        $generator = new ChromePdfGenerator();

        $command = new GeneratePdfCommand($kernel, $generator);
        $tester  = new CommandTester($command);

        $exitCode = $tester->execute([
            'input'  => $inputFile,
            'output' => $outputFile,
        ]);

        self::assertSame(Command::FAILURE, $exitCode);
        self::assertStringContainsString('Unable to create output directory', $tester->getDisplay());
    }
}

final class TestKernel implements KernelInterface
{
    public function __construct(private readonly string $projectDir)
    {
    }

    public function registerBundles(): iterable
    {
        return [];
    }

    public function boot(): void
    {
    }

    public function shutdown(): void
    {
    }

    public function getBundles(): array
    {
        return [];
    }

    public function getBundle(string $name): BundleInterface
    {
        throw new \RuntimeException('No bundles registered.');
    }

    public function locateResource(string $name): string
    {
        throw new \RuntimeException('No resources available.');
    }

    public function registerContainerConfiguration(LoaderInterface $loader): void
    {
        throw new \RuntimeException('No container configuration available.');
    }

    public function getProjectDir(): string
    {
        return $this->projectDir;
    }

    public function getEnvironment(): string
    {
        return 'test';
    }

    public function isDebug(): bool
    {
        return true;
    }

    public function getContainer(): ContainerInterface
    {
        throw new \RuntimeException('No container available.');
    }

    public function getStartTime(): float
    {
        return \microtime(true);
    }

    public function getCacheDir(): string
    {
        return $this->projectDir . '/var/cache/test';
    }

    public function getBuildDir(): string
    {
        return $this->projectDir . '/var/build';
    }

    public function getLogDir(): string
    {
        return $this->projectDir . '/var/log';
    }

    public function getCharset(): string
    {
        return 'UTF-8';
    }

    public function handle(Request $request, int $type = self::MAIN_REQUEST, bool $catch = true): Response
    {
        throw new \RuntimeException('HTTP handling is not available.');
    }
}
